// TypeScript domain models for Apex Study OS

export type WeaknessLevel = 'low' | 'medium' | 'high';
export type SyllabusStatus = 'not_started' | 'in_progress' | 'completed' | 'revision_phase' | 'mastered';
export type ChapterStatus = 'not_started' | 'learning' | 'practicing' | 'revision' | 'mastered';
export type Difficulty = 'easy' | 'medium' | 'hard';
export type PriorityLevel = 'urgent' | 'high' | 'medium' | 'low';
export type TaskStatus = 'pending' | 'in_progress' | 'completed' | 'skipped';
export type TaskType = 
  | 'learning' 
  | 'practice' 
  | 'revision' 
  | 'mock_test' 
  | 'error_correction' 
  | 'active_recall' 
  | 'formula_sheet';

export type ErrorCategory = 
  | 'conceptual' 
  | 'calculation' 
  | 'formula' 
  | 'careless' 
  | 'time_management';

export interface UserProfile {
  name: string;
  classGrade: string;
  schoolName?: string; // e.g. "Gyan Niketan"
  examName: string;
  targetExamDate: string; // "2026-09-18"
  targetScore?: string; // e.g. "95%+ Distinction"
  preferredStudySlot?: 'morning' | 'afternoon' | 'evening' | 'night_owl';
  aiTutorTone?: 'encouraging' | 'strict_cbse' | 'conceptual_socratic';
  pomodoroMinutes?: number;
  studyPreference: {
    schoolDaysHours: number; // e.g. 3.5 hrs
    weekendHours: number;    // e.g. 6.5 hrs
    subjectAllocation: Record<string, number>; // e.g. { 'maths': 45, 'science': 30, 'english': 15, 'others': 10 }
  };
  completedOnboarding: boolean;
  theme: 'dark' | 'light';
  soundEnabled: boolean;
  // NVIDIA NIM AI Configuration
  nvidiaApiKey?: string;
  nvidiaModel?: string; // e.g. "meta/llama-3.2-11b-vision-instruct"
  nvidiaBaseUrl?: string;
}

export interface Exam {
  id: string;
  subjectId: string;
  subjectName: string;
  date: string; // ISO "2026-09-18"
  startTime: string; // "09:00 AM"
  durationMinutes: number; // 180
  totalMarks: number; // 80 or 100
  targetMarks?: number;
  weightage: number; // in percentage
  notes?: string;
}

export interface Subject {
  id: string;
  name: string;
  code: string;
  color: string; // Tailwind hex or class e.g. '#6366f1'
  icon: string;
  isWeak: boolean;
  weaknessLevel: WeaknessLevel;
  syllabusStatus: SyllabusStatus;
  priorityWeight: number; // dynamically computed or manual override
  examDate: string;
  targetStudyHours: number;
  completedStudyHours: number;
  category?: 'core' | 'language' | 'applied' | 'elective';
  subBranches?: string[]; // e.g. ['Physics', 'Chemistry', 'Biology']
}

export interface Chapter {
  id: string;
  subjectId: string;
  subBranch?: string; // e.g. "Physics" inside Science
  name: string;
  order: number;
  difficulty: Difficulty;
  confidenceLevel: 1 | 2 | 3 | 4 | 5; // 1 (Confused) to 5 (Mastered)
  completionPercentage: number; // 0 to 100
  status: ChapterStatus;
  isMastered: boolean;
  questionsSolved: number;
  targetQuestions: number;
  lastRevisedDate: string | null;
  nextRevisionDate: string | null;
  revisionCount: number;
  maxRevisionInterval?: number;
  notes: string;
  mistakesCount: number;
  importantFormulas?: string[];
  keyTopics?: string[];
  bookPageRange?: string; // e.g. "Page 98 - 115"
}

export interface StudyTask {
  id: string;
  title: string;
  subjectId: string;
  chapterId?: string;
  taskType: TaskType;
  estimatedMinutes: number;
  actualMinutes?: number;
  scheduledDate: string; // YYYY-MM-DD
  scheduledTime?: string; // "16:30"
  priority: PriorityLevel;
  priorityScore: number;
  status: TaskStatus;
  completedAt?: string;
  skippedReason?: string;
  rescheduledTo?: string;
  notes?: string;
  isAutoGenerated: boolean;
  orderIndex: number;
}

export interface RevisionItem {
  id: string;
  subjectId: string;
  chapterId: string;
  stage: 1 | 2 | 3 | 4 | 5; // 1d, 3d, 7d, 14d, Pre-Exam
  dueDate: string; // YYYY-MM-DD
  intervalDays: number;
  status: 'due' | 'completed' | 'overdue';
  lastStudiedDate: string;
  confidenceBefore: number;
  confidenceAfter?: number;
  notes?: string;
}

export interface ErrorLog {
  id: string;
  subjectId: string;
  chapterId?: string;
  chapterName?: string;
  mistake: string;
  category: ErrorCategory;
  correctedUnderstanding: string;
  date: string;
  occurrenceCount: number;
  source: string; // e.g. "Mock 2", "NCERT Ex 4.2", "Pythagoras Theorem Practice"
  severity?: 'critical' | 'moderate' | 'minor';
  aiRemediationNotes?: string;
}

export interface MockTest {
  id: string;
  subjectId: string;
  title: string; // "Maths Mock 1 — Full Syllabus"
  date: string;
  durationMinutes: number;
  score: number;
  totalMarks: number;
  percentage: number;
  weakTopics: string[];
  mistakesCount: number;
  notes: string;
  keyTakeaways: string;
  isAiGenerated?: boolean;
}

export interface InteractiveQuizQuestion {
  id: string;
  question: string;
  options?: string[]; // for MCQ
  correctOptionIndex?: number;
  modelAnswer: string;
  marks: number;
  type: 'mcq' | 'numerical' | 'short' | 'proof';
  topic: string;
  userAnswer?: string;
  userScore?: number;
  feedback?: string;
}

export interface InteractiveMockExam {
  id: string;
  subjectId: string;
  title: string;
  durationMinutes: number;
  totalMarks: number;
  instructions: string[];
  questions: InteractiveQuizQuestion[];
  createdDate: string;
  status: 'draft' | 'in_progress' | 'evaluated';
  studentScore?: number;
  aiEvaluationSummary?: string;
}

export interface BookChapterFile {
  chapterId?: string;
  chapterNumber?: number;
  name: string;
  pdfPath: string;
  pageStart?: number;
}

export interface BookDocument {
  id: string;
  title: string;
  classGrade?: string; // 'Class 7' | 'Class 8' | 'Class 9' | 'Class 10'
  subjectId: string;
  subjectName?: string;
  folderPath?: string;
  fileName: string;
  fileUrl: string;
  fileSize?: string;
  uploadedAt: string;
  chapterFiles?: BookChapterFile[];
  chaptersMap?: {
    chapterId?: string;
    name: string;
    pageStart: number;
    pdfPath?: string;
  }[];
}

export interface StudySessionLog {
  id: string;
  taskId?: string;
  subjectId: string;
  chapterId?: string;
  durationMinutes: number;
  date: string;
  timestamp: number;
  confidenceRating: 1 | 2 | 3 | 4 | 5;
  taskType: string;
  notes: string;
}

export interface AppState {
  user: UserProfile;
  exams: Exam[];
  subjects: Subject[];
  chapters: Chapter[];
  tasks: StudyTask[];
  revisions: RevisionItem[];
  errorLogs: ErrorLog[];
  mockTests: MockTest[];
  sessionLogs: StudySessionLog[];
  books: BookDocument[];
  interactiveMocks: InteractiveMockExam[];
  activeView: NavigationTab;
  currentDate: string; // Virtual clock date (defaults to today / 2026-08-30)
}

export type NavigationTab = 
  | 'dashboard'
  | 'plan'
  | 'calendar'
  | 'subjects'
  | 'chapters'
  | 'revision'
  | 'errors'
  | 'mocks'
  | 'ai-tutor'
  | 'books'
  | 'analytics'
  | 'focus'
  | 'exams'
  | 'settings';
